apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: gateway-crds-helm
    repo: oci://docker.io/envoyproxy
    version: 1.6.3
    includeCRDs: true
    valuesFile: valuesEnvoyGateway.yaml
