apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - resources/certManager.yaml
  - resources/gatewayApi.yaml
  - resources/istio.yaml
  - resources/longhorn.yaml

# Other namespaces
# argocd            is created by opentofu when i bootstrap the kubernetes cluster
# cert-manager      creates its own namespace. its in the static yaml file cert-manager provides.
#                     i'm commenting out my namespace file and leaving the file in the repo for the time being.
# cilium-secrets    is created by cilium when the cluster is bootstrapped
