apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/certManager.yaml
  - resources/envoyGateway.yaml
  - resources/gatewayApi.yaml
  - resources/longhorn.yaml

# Other namespaces
# argocd            is created by opentofu when i bootstrap the kubernetes cluster
# cilium-secrets    is created by cilium when the cluster is bootstrapped
