apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: base # istio base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.28.3
    namespace: istio-system
    includeCRDs: true
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/standard-install.yaml # gateway api standard channel
