apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/sleep.yaml
  - resources/sleep2.yaml
  - resources/gatewayClass.yaml
  - resources/gatewayTlsTerminationCertificate.yaml
  - resources/gateway.yaml
  - resources/routeHttpToHttpsRedirect.yaml
