apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/huntInternalDevelopmentHomeTlsTerminationCertificate.yaml
  - resources/huntInternalDevelopmentLabTlsTerminationCertificate.yaml
  - resources/huntInternalProductionHomeTlsTerminationCertificate.yaml
  - resources/huntInternalProductionLabTlsTerminationCertificate.yaml
  - resources/gatewayClass.yaml
  - resources/gatewayHuntInternalDevelopmentHome.yaml
  - resources/gatewayHuntInternalDevelopmentLab.yaml
  - resources/gatewayHuntInternalProductionHome.yaml
  - resources/gatewayHuntInternalProductionLab.yaml
  - resources/routeArgocd.yaml
  - resources/routeLonghorn.yaml
